### ISSUE TITLE
1.0 tag doesn't work in DEPS

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/http_parser#5]
In all other packages I've been able to depend on specific commit hashes via git tags, for example, '@0.10.0'. However for the http_parser repository the 1.0.0 tag doesn't work. I'm not sure why but git complains about it not being a "tree".

**Comment by nex3** [comment]
I don't think that's an issue with this repo. The 1.0.0 tag [is right here](https://github.com/dart-lang/http_parser/releases/tag/1.0.0), and doesn't seem to be any different than any other tag in any other repository. Maybe the Chrome mirror missed it somehow?

**Comment by whesse** [comment]
The mirror stopped mirroring http_parser three weeks ago.  This usually happens if someone does a force push to a repo that changes history.  Anything other than fast forward pages and merges breaks mirroring.  I'll fix this by rolling back to the last mirrored state, and merging the history since then.  I'll send out a message to the whole team about mirroring repos.

**Comment by nex3** [comment]
@whesse why was this re-opened?

**Comment by whesse** [comment]
Because it was an issue with this repo, and the fix was to do something to this repo.  It is now fixed, I forgot to close it.
